Search.appendIndex(
    [
                {
            "fqsen": "\\hashPassword\u0028\u0029",
            "name": "hashPassword",
            "summary": "Zwraca\u0020hash\u0020has\u0142a\u0020zaszyfrowanego\u0020Argonem2ID.",
            "url": "../namespaces/default.html#function_hashPassword"
        },                {
            "fqsen": "\\isValidCaptcha\u0028\u0029",
            "name": "isValidCaptcha",
            "summary": "Sprawdza\u0020czy\u0020captcha\u0020jest\u0020zweryfikowana\u0020przez\u0020Google\u0020i\u0020nie\u0020wygas\u0142a.",
            "url": "../namespaces/default.html#function_isValidCaptcha"
        },                {
            "fqsen": "\\sendMail\u0028\u0029",
            "name": "sendMail",
            "summary": "Wysy\u0142a\u0020wiadomo\u015B\u0107\u0020na\u0020podany\u0020email,\u0020z\u0020danym\u0020tytu\u0142em\u0020i\u0020dan\u0105\u0020tre\u015Bci\u0105\u0020\u0028mo\u017Ce\u0020zawiera\u0107\u0020kod\u0020HTML\u0029.",
            "url": "../namespaces/default.html#function_sendMail"
        },                {
            "fqsen": "\\verifyPassword\u0028\u0029",
            "name": "verifyPassword",
            "summary": "Weryfikuje\u0020has\u0142o\u0020na\u0020podstawie\u0020hasha.",
            "url": "../namespaces/default.html#function_verifyPassword"
        },                {
            "fqsen": "\\UserStatuses",
            "name": "UserStatuses",
            "summary": "",
            "url": "../classes/UserStatuses.html"
        },                {
            "fqsen": "\\UserStatuses\u003A\u003AgetStatusIndex\u0028\u0029",
            "name": "getStatusIndex",
            "summary": "",
            "url": "../classes/UserStatuses.html#method_getStatusIndex"
        },                {
            "fqsen": "\\UserStatuses\u003A\u003AgetStatusName\u0028\u0029",
            "name": "getStatusName",
            "summary": "",
            "url": "../classes/UserStatuses.html#method_getStatusName"
        },                {
            "fqsen": "\\UserStatuses\u003A\u003A\u0024statuses",
            "name": "statuses",
            "summary": "",
            "url": "../classes/UserStatuses.html#property_statuses"
        },                {
            "fqsen": "\\User",
            "name": "User",
            "summary": "",
            "url": "../classes/User.html"
        },                {
            "fqsen": "\\User\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "../classes/User.html#method___construct"
        },                {
            "fqsen": "\\User\u003A\u003AisLogged\u0028\u0029",
            "name": "isLogged",
            "summary": "",
            "url": "../classes/User.html#method_isLogged"
        },                {
            "fqsen": "\\User\u003A\u003AsetUserData\u0028\u0029",
            "name": "setUserData",
            "summary": "",
            "url": "../classes/User.html#method_setUserData"
        },                {
            "fqsen": "\\User\u003A\u003AgetUserData\u0028\u0029",
            "name": "getUserData",
            "summary": "",
            "url": "../classes/User.html#method_getUserData"
        },                {
            "fqsen": "\\User\u003A\u003AlogUser\u0028\u0029",
            "name": "logUser",
            "summary": "",
            "url": "../classes/User.html#method_logUser"
        },                {
            "fqsen": "\\User\u003A\u003AgenerateToken\u0028\u0029",
            "name": "generateToken",
            "summary": "",
            "url": "../classes/User.html#method_generateToken"
        },                {
            "fqsen": "\\User\u003A\u003AgetToken\u0028\u0029",
            "name": "getToken",
            "summary": "",
            "url": "../classes/User.html#method_getToken"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024userId",
            "name": "userId",
            "summary": "",
            "url": "../classes/User.html#property_userId"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024login",
            "name": "login",
            "summary": "",
            "url": "../classes/User.html#property_login"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "../classes/User.html#property_email"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024firstname",
            "name": "firstname",
            "summary": "",
            "url": "../classes/User.html#property_firstname"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024lastname",
            "name": "lastname",
            "summary": "",
            "url": "../classes/User.html#property_lastname"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024status",
            "name": "status",
            "summary": "",
            "url": "../classes/User.html#property_status"
        },                {
            "fqsen": "\\throwError\u0028\u0029",
            "name": "throwError",
            "summary": "Ko\u0144czy\u0020dzia\u0142anie\u0020skryptu\u0020i\u0020wy\u015Bwietla\u0020b\u0142\u0105d\u0020w\u0020formacie\u0020JSON\u0020\u007B\u0020error\u003A\u0020\u0024name\u0020\u007D",
            "url": "../namespaces/default.html#function_throwError"
        },                {
            "fqsen": "\\success\u0028\u0029",
            "name": "success",
            "summary": "Pozytywnie\u0020ko\u0144czy\u0020dzia\u0142anie\u0020skryptu\u0020i\u0020wy\u015Bwietla\u0020JSON\u0020\u007B\u0020success\u003A\u0020true\u0020\u007D",
            "url": "../namespaces/default.html#function_success"
        },                {
            "fqsen": "\\getRandomText\u0028\u0029",
            "name": "getRandomText",
            "summary": "Zwraca\u0020ci\u0105g\u0020losowych\u0020znak\u00F3w\u0020o\u0020podanej\u0020d\u0142ugo\u015Bci",
            "url": "../namespaces/default.html#function_getRandomText"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "../namespaces/default.html"
        }            ]
);
